#!/bin/sh
# Thanks to KenT for contributions

RET=0

while [ $RET -eq 0 ]; do
  GAME=$(zenity --width=350 --height=700 --list \
    --title="Ace Penguin Card Games" \
    --text="Note: In the near future you will have to use points to play these games." \
    --column="Script name" --column="Description" \
    ace-canfield "Ace Canfield" \
    ace-freecell "Ace Freecell" \
    ace-golf "Ace Golf" \
    ace-mastermind "Ace Mastermind" \
    ace-merlin "Ace Merlin" \
    ace-minesweeper "Ace Minesweeper" \
    ace-pegged "Ace Pegged" \
    ace-solitaire "Ace Solitaire" \
    ace-spider "Ace Spider" \
    ace-taipei "Ace Taipei" \
    ace-thornq "Ace Thornq" \
)
    
  RET=$?
  echo $RET
  if [ "$RET" -eq 0 ]
  then
     if [ "$GAME" = "website" ]
     then
        sensible-browser "http://inventwithpython.com/pygame"
     else
       if [ "$GAME" != "" ]; then
          /usr/games/$GAME
       fi
     fi
  fi
done
